export const SET_WEATHER_REPORT = 'SET_WEATHER_REPORT';
export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_CITIES = 'FETCH_CITIES';
export const SET_SEARCHED_CITIES = 'SET_SEARCHED_CITIES';